load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_protoc_dev",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg=bz_build",
    ],
    deps = [
        "fbsource//third-party/rust:tonic-prost-build",
    ],
)
