
oncall("build_infra")

rust_library(
    name = "bz_protoc_dev",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg=bz_build",
    ],
    deps = [
        "third_party//rust:tonic-prost-build",
    ],
)
