load("//tests:buck_e2e.bzl", "bz_e2e_test")

oncall("tae")

python_library(
    name = "fdb_e2e_types",
    srcs = ["types.py"],
    deps = [
        "//tests/e2e_util/api:api",
    ],
)

bz_e2e_test(
    name = "test_fdb_project",
    srcs = [
        "test_fdb_bxl_java.py",
    ],
    test_with_compiled_buck2 = False,
    test_with_deployed_buck2 = True,
    deps = [
        ":fdb_e2e_types",
        "//tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
