
oncall("build_infra")

rust_library(
    name = "bz_env",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "third_party//rust:assert_matches",
    ],
    deps = [
        "third_party//rust:arc-swap",
        "third_party//rust:linkme",
        "third_party//rust:once_cell",
        "third_party//rust:tracing",
        "//app/bz_error:bz_error",
        "//deps/gazebo/dupe:dupe",
        "//deps/starlark-rust/starlark_map:starlark_map",
    ],
)
