load("@fbcode//bz/tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

bz_e2e_test(
    name = "test_buck_config_logging.py",
    srcs = ["test_buck_config_logging.py"],
    data_dir = "test_buck_config_log_data",
)
