load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_sketches",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:base64",
        "//bz/deps/setsketch:setsketch",
    ],
)
