load("@fbcode//bz:proto_defs.bzl", "proto_srcs", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "bz_action_metadata_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bz_action_metadata_proto.proto",
)

proto_srcs(
    name = "bz_action_metadata_proto.proto",
    srcs = ["action_metadata.proto"],
    visibility = ["PUBLIC"],
)
