
oncall("build_infra")

rust_library(
    name = "bz_build_api_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "third_party//rust:convert_case",
        "third_party//rust:proc-macro2",
        "third_party//rust:quote",
        "third_party//rust:syn",
        "//deps/gazebo/gazebo:gazebo",
    ],
)
