
oncall("build_infra")

rust_library(
    name = "bz_grpc",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "third_party//rust:futures",
        "third_party//rust:hyper",
        "third_party//rust:hyper-util",
        "third_party//rust:pin-project",
        "third_party//rust:tokio",
        "third_party//rust:tonic",
        "third_party//rust:tower",
        "//app/bz_error:bz_error",
    ],
)
