load("@fbcode//bz/tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

bz_e2e_test(
    name = "test_what_ran",
    srcs = ["test_what_ran.py"],
    use_compiled_bz_client_and_tpx = True,
)

bz_e2e_test(
    name = "test_what_failed",
    srcs = ["test_what_failed.py"],
)

bz_e2e_test(
    name = "test_log_format",
    srcs = ["test_log_format.py"],
    use_compiled_bz_client_and_tpx = True,
)

bz_e2e_test(
    name = "test_persist_event_logs",
    srcs = ["test_persist_event_logs.py"],
    deps = [
        "//manifold/clients/python:manifold_client_deprecated",
    ],
)
