load("@fbcode//bz/tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

bz_e2e_test(
    name = "test_starlark",
    srcs = ["test_starlark.py"],
)

bz_e2e_test(
    name = "test_linker_argsfile",
    srcs = ["test_linker_argsfile.py"],
)

bz_e2e_test(
    name = "test_lsp_fbsource",
    srcs = ["test_lsp_fbsource.py"],
)

bz_e2e_test(
    name = "test_cpp_gen_cdb",
    srcs = ["test_cpp_gen_cdb.py"],
)

bz_e2e_test(
    name = "test_tools",
    srcs = ["test_tools.py"],
    test_with_deployed_buck2 = True,
    use_compiled_bz_client_and_tpx = True,
)

bz_e2e_test(
    name = "test_install_modifiers",
    srcs = ["test_install_modifiers.py"],
    deps = [
        "fbcode//bz/tests/e2e_util:utils",
    ],
)
