
oncall("build_infra")

visibility = ["PUBLIC"]

python_library(
    name = "api",
    srcs = glob(["*.py"]),
    # This is not public API for buck invocation, but a part of bz_e2e testing framwork.
    # We may want to make it public API, and when we do, let's do it explicitly:
    # * clean
    # * with tests
    # * with public announcement
    visibility = visibility,
)
