load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "buck2_action_impl_tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:maplit",
        "//bz/app/bz_action_impl:buck2_action_impl",
        "//bz/app/bz_anon_target:buck2_anon_target",
        "//bz/app/bz_build_api:buck2_build_api",
        "//bz/app/bz_core:buck2_core",
        "//bz/app/bz_error:buck2_error",
        "//bz/app/bz_execute:buck2_execute",
        "//bz/app/bz_interpreter:buck2_interpreter",
        "//bz/app/bz_interpreter_for_build:buck2_interpreter_for_build",
        "//bz/gazebo/dupe:dupe",
        "//bz/starlark-rust/starlark:starlark",
    ],
)
