
oncall("build_infra")

rust_test(
    name = "bz_action_impl_tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "third_party//rust:ctor",
        "third_party//rust:indoc",
        "third_party//rust:maplit",
        "//app/bz_action_impl:bz_action_impl",
        "//app/bz_anon_target:bz_anon_target",
        "//app/bz_build_api:bz_build_api",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_execute:bz_execute",
        "//app/bz_interpreter:bz_interpreter",
        "//app/bz_interpreter_for_build:bz_interpreter_for_build",
        "//deps/gazebo/dupe:dupe",
        "//deps/starlark-rust/starlark:starlark",
    ],
)
