load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bz_action_impl_tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:maplit",
        "//bz/app/bz_action_impl:bz_action_impl",
        "//bz/app/bz_anon_target:bz_anon_target",
        "//bz/app/bz_build_api:bz_build_api",
        "//bz/app/bz_core:bz_core",
        "//bz/app/bz_error:bz_error",
        "//bz/app/bz_execute:bz_execute",
        "//bz/app/bz_interpreter:bz_interpreter",
        "//bz/app/bz_interpreter_for_build:bz_interpreter_for_build",
        "//bz/gazebo/dupe:dupe",
        "//bz/starlark-rust/starlark:starlark",
    ],
)
