
oncall("build_infra")

rust_library(
    name = "bz_test_runner",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:clap",
        "third_party//rust:futures",
        "third_party//rust:parking_lot",
        "third_party//rust:prost",
        "third_party//rust:sorted_vector_map",
        "third_party//rust:tokio",
        "//app/bz_error:bz_error",
        "//app/bz_grpc:bz_grpc",
        "//app/bz_test_api:bz_test_api",
        "//app/bz_test_proto:bz_test_proto",
        "//deps/host_sharing:host_sharing",
    ],
)
