load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_test_runner",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:sorted_vector_map",
        "fbsource//third-party/rust:tokio",
        "//bz/app/bz_error:bz_error",
        "//bz/app/bz_grpc:bz_grpc",
        "//bz/app/bz_test_api:bz_test_api",
        "//bz/host_sharing:host_sharing",
    ],
)
