# @oss-disable[end= ]: load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "main",
    srcs = ["src/main.rs"],
    deps = [
        "fbcode//bz/docs/bz_lab/greeter_lib:library",
        "fbcode//bz/docs/bz_lab/logging_lib:logging_lib",
    ],
)
