load("//tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

python_binary(
    # @autodeps-skip
    name = "health_check_server_bin",
    srcs = [
        "health_check_server.py",
    ],
    main_function = "buck2.tests.e2e.health_check.health_check_server.main",
    visibility = ["PUBLIC"],
    deps = [
        "//app/bz_health_check_proto:health_check-py",
        "third_party//grpc/src/python/grpcio/grpc:grpcio",
    ],
)

bz_e2e_test(
    name = "test_health_check",
    srcs = ["test_health_check.py"],
    skip_for_os = [
        "windows",
    ],
    deps = [
        "//tests/e2e_util:utils",
    ],
)
