load("//rust:linkable_symbol.bzl", "rust_linkable_symbol")

oncall("build_infra")

rust_library(
    name = "bz_cmd_completion_client",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["third_party//rust:paste"],
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:clap",
        "third_party//rust:clap_complete",
        "third_party//rust:futures",
        "third_party//rust:tokio",
        ":completion_wrapper_bash",
        ":completion_wrapper_fish",
        ":completion_wrapper_zsh",
        ":options_wrapper_bash",
        ":options_wrapper_fish",
        ":options_wrapper_zsh",
        "//app/bz_cli_proto:bz_cli_proto",
        "//app/bz_client_ctx:bz_client_ctx",
        "//app/bz_common:bz_common",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_fs:bz_fs",
        "//deps/bz_hash:bz_hash",
    ],
)

rust_linkable_symbol(
    name = "completion_wrapper_bash",
    content_str = "src/completion/completion-wrapper.bash",
)

rust_linkable_symbol(
    name = "completion_wrapper_fish",
    content_str = "src/completion/completion-wrapper.fish",
)

rust_linkable_symbol(
    name = "completion_wrapper_zsh",
    content_str = "src/completion/completion-wrapper.zsh",
)

rust_linkable_symbol(
    name = "options_wrapper_bash",
    content_str = "src/completion/options-wrapper.bash",
)

rust_linkable_symbol(
    name = "options_wrapper_fish",
    content_str = "src/completion/options-wrapper.fish",
)

rust_linkable_symbol(
    name = "options_wrapper_zsh",
    content_str = "src/completion/options-wrapper.zsh",
)
