
oncall("build_infra")

rust_library(
    name = "bz_cmd_audit_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:clap",
        "third_party//rust:serde",
        "third_party//rust:serde_json",
        "//app/bz_cli_proto:bz_cli_proto",
        "//app/bz_client_ctx:bz_client_ctx",
        "//deps/gazebo/dupe:dupe",
    ],
)
