load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "remote_execution",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:tempfile",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-compression",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:http",
        "fbsource//third-party/rust:hyper",
        "fbsource//third-party/rust:hyper-util",
        "fbsource//third-party/rust:lru",
        "fbsource//third-party/rust:once_cell",
        "fbsource//third-party/rust:prost",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-util",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tower",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:uuid",
        "//bz/app/bz_re_configuration:bz_re_configuration",
        "//bz/app/bz_util:bz_util",
        "//bz/gazebo/dupe:dupe",
        "//bz/gazebo/gazebo:gazebo",
        "//bz/remote_execution/oss/re_grpc_proto:re_grpc_proto",
    ],
)
