
oncall("build_infra")

rust_library(
    name = "bz_query_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "third_party//rust:itertools",
        "third_party//rust:proc-macro2",
        "third_party//rust:quote",
        "third_party//rust:syn",
        "third_party//rust:textwrap",
    ],
)
