
oncall("build_infra")

rust_library(
    name = "bz_validation",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:derivative",
        "third_party//rust:derive_more",
        "third_party//rust:either",
        "third_party//rust:futures",
        "third_party//rust:serde",
        "third_party//rust:serde_json",
        "//deps/allocative/allocative:allocative",
        "//app/bz_artifact:bz_artifact",
        "//app/bz_build_api:bz_build_api",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_execute:bz_execute",
        "//app/bz_fs:bz_fs",
        "//deps/dice/dice:dice",
        "//deps/dice/dice_error:dice_error",
        "//deps/gazebo/dupe:dupe",
        "//deps/pagable:pagable",
    ],
)
