load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bz_node_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//bz/app/bz_core:bz_core",
        "//bz/app/bz_error:bz_error",
        "//bz/app/bz_fs:bz_fs",
        "//bz/app/bz_node:bz_node",
        "//bz/app/bz_util:bz_util",
        "//bz/gazebo/dupe:dupe",
    ],
)
