
oncall("build_infra")

rust_test(
    name = "bz_node_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_fs:bz_fs",
        "//app/bz_node:bz_node",
        "//app/bz_util:bz_util",
        "//deps/gazebo/dupe:dupe",
    ],
)
