load("//tests:buck_e2e.bzl", "bz_core_tests")

oncall("build_infra")

bz_core_tests(
    target_extra_attrs = {
        "test_subscribe": {
            "env": {
                "BUCK2_EXPECT": "$(exe_target //tests/core/subscribe/buck2_expect:buck2_expect)",
            },
        },
    },
)
