load("//:rules/proto_defs.bzl", "proto_srcs", "rust_protobuf_library")
load("//rules:grpc.bzl", "grpc_library")

oncall("build_infra")

rust_protobuf_library(
    name = "bz_subscription_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bz_subscription_proto.proto",
    deps = [
        "third_party//rust:derive_more",
        "third_party//rust:serde",
        "//deps/allocative/allocative:allocative",
    ],
)

proto_srcs(
    name = "bz_subscription_proto.proto",
    srcs = ["subscription.proto"],
    visibility = ["PUBLIC"],
)

grpc_library(
    name = "subscription",
    srcs = [
        "subscription.proto",
    ],
    languages = [
        "py",
    ],
)

export_file(
    name = "subscription.proto",
)
