load("//tests:buck_e2e.bzl", "bz_core_tests")

oncall("build_infra")

bz_core_tests(
    target_extra_attrs = {
        "test_help_env": {
            "use_compiled_bz_client_and_tpx": True,
        },
    },
)
