load("@fbcode//bz/tests:buck_e2e.bzl", "bz_core_tests")

oncall("build_infra")

bz_core_tests(
    target_extra_attrs = {
        "test_console": {
            "env": {
                "FIXTURES": "$(location //bz/tests/core/console/fixtures:fixtures)",
            },
        },
        "test_console_output_limit": {
            "use_compiled_bz_client_and_tpx": True,
        },
    },
)
