
oncall("build_infra")

rust_library(
    name = "bz_critical_path",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "third_party//rust:rand",
        "third_party//rust:rand_chacha",
        "third_party//rust:rand_distr",
    ],
    deps = [
        "third_party//rust:crossbeam",
        "third_party//rust:derive_more",
        "//app/bz_error:bz_error",
        "//deps/starlark-rust/starlark_map:starlark_map",
    ],
)
