load("@fbcode//bz/tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

bz_e2e_test(
    name = "test_lazy_utils",
    srcs = ["test_lazy_utils.py"],
    data = "//bz/tests/targets:isolated_targets",
    env = {
        "PRELUDE": "$(location prelude//:prelude)",
    },
)
