load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("ios_pika")

source_listing()

cxx_binary(
    name = "native_dist_lto_planner",
    srcs = [
        "dist_lto_planner.cpp",
    ],
    compiler_flags = [
        "-Wno-deprecated-declarations",
        "-O2",
    ],
    linker_flags = [
        "-lc",
    ],
    target_compatible_with = ["prelude//:none"],
    visibility = ["PUBLIC"],
    deps = [],
)
