load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_test_api",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tower-layer",
        "fbsource//third-party/rust:tower-service",
        "fbsource//third-party/rust:tracing",
        "//bz/allocative/allocative:allocative",
        "//bz/app/bz_core:buck2_core",
        "//bz/app/bz_downward_api:buck2_downward_api",
        "//bz/app/bz_downward_api_proto:buck2_downward_api_proto",
        "//bz/app/bz_error:buck2_error",
        "//bz/app/bz_events:buck2_events",
        "//bz/app/bz_fs:buck2_fs",
        "//bz/app/bz_grpc:buck2_grpc",
        "//bz/app/bz_host_sharing_proto:buck2_host_sharing_proto",
        "//bz/app/bz_test_proto:buck2_test_proto",
        "//bz/gazebo/dupe:dupe",
        "//bz/gazebo/gazebo:gazebo",
        "//bz/host_sharing:host_sharing",
        "//bz/pagable:pagable",
        "//bz/shed/buck2_hash:buck2_hash",
        "//common/rust/shed/sorted_vector_map:sorted_vector_map",
    ],
)
