
oncall("build_infra")

rust_library(
    name = "bz_test_api",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "third_party//rust:assert_matches",
    ],
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:derivative",
        "third_party//rust:derive_more",
        "third_party//rust:futures",
        "third_party//rust:prost-types",
        "third_party//rust:tokio",
        "third_party//rust:tonic",
        "third_party//rust:tower-layer",
        "third_party//rust:tower-service",
        "third_party//rust:tracing",
        "//deps/allocative/allocative:allocative",
        "//app/bz_core:bz_core",
        "//app/bz_downward_api:bz_downward_api",
        "//app/bz_downward_api_proto:bz_downward_api_proto",
        "//app/bz_error:bz_error",
        "//app/bz_events:bz_events",
        "//app/bz_fs:bz_fs",
        "//app/bz_grpc:bz_grpc",
        "//app/bz_host_sharing_proto:bz_host_sharing_proto",
        "//app/bz_test_proto:bz_test_proto",
        "//deps/gazebo/dupe:dupe",
        "//deps/gazebo/gazebo:gazebo",
        "//deps/host_sharing:host_sharing",
        "//deps/pagable:pagable",
        "//deps/bz_hash:bz_hash",
        "//common/rust/shed/sorted_vector_map:sorted_vector_map",
    ],
)
