load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_test_api",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tower-layer",
        "fbsource//third-party/rust:tower-service",
        "fbsource//third-party/rust:tracing",
        "//bz/deps/allocative/allocative:allocative",
        "//bz/app/bz_core:bz_core",
        "//bz/app/bz_downward_api:bz_downward_api",
        "//bz/app/bz_downward_api_proto:bz_downward_api_proto",
        "//bz/app/bz_error:bz_error",
        "//bz/app/bz_events:bz_events",
        "//bz/app/bz_fs:bz_fs",
        "//bz/app/bz_grpc:bz_grpc",
        "//bz/app/bz_host_sharing_proto:bz_host_sharing_proto",
        "//bz/app/bz_test_proto:bz_test_proto",
        "//bz/deps/gazebo/dupe:dupe",
        "//bz/deps/gazebo/gazebo:gazebo",
        "//bz/deps/host_sharing:host_sharing",
        "//bz/deps/pagable:pagable",
        "//bz/deps/bz_hash:bz_hash",
        "//common/rust/shed/sorted_vector_map:sorted_vector_map",
    ],
)
