load("@fbcode//bz/tests:buck_e2e.bzl", "bz_core_tests")

oncall("build_infra")

bz_core_tests(
    target_extra_attrs = {
        "test_explain": {
            "deps": [
                "//manifold/clients/python:manifold_client_deprecated",
            ],
        },
    },
)
