
oncall("build_infra")

rust_binary(
    name = "bz_miniperf",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    allocator = "malloc",
    allow_cache_upload = True,
    # JEMalloc isn't super lean (and we don't actually allocate anything here),
    # so dont use it.
    default_strip_mode = "full",
    # Must be statically linked because the binary is embedded in the forkserver
    # and written to disk without its shared library dependencies.
    link_style = "static",
    deps = [
        "third_party//rust:anyhow",
    ] + select({
        # Ideally we'd use compatible_with, but TD does not understand that.
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "third_party//rust:bincode",
            "third_party//rust:perf-event",
            "third_party//rust:smallvec",
            "third_party//rust:thiserror",
            "//app/bz_miniperf_proto:bz_miniperf_proto",
        ],
    }),
)

# TODO
rust_library(
    name = "bz_miniperf_test",
    srcs = glob(
        ["test/**/*.rs"],
    ),
    test_deps = select({
        # Ideally we'd use compatible_with, but TD does not understand that.
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "third_party//rust:anyhow",
            "third_party//rust:bincode",
            "third_party//rust:tempfile",
            "//app/bz_miniperf_proto:bz_miniperf_proto",
        ],
    }),
    test_env = {
        "MINIPERF": "$(exe_target :bz_miniperf)",
        "THREE_BILLION_INSTRUCTIONS": "$(exe_target //deps/three_billion_instructions:three_billion_instructions-bin)",
    },
)
