
oncall("build_infra")

rust_binary(
    name = "buck2_expect",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "third_party//rust:anyhow",
        "third_party//rust:clap",
        "third_party//rust:futures",
        "third_party//rust:prost",
        "third_party//rust:tokio",
        "third_party//rust:tokio-util",
        "//app/bz_cli_proto:bz_cli_proto",
        "//app/bz_subscription_proto:bz_subscription_proto",
    ],
)
