load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "buck2_expect",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:prost",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-util",
        "//bz/app/bz_cli_proto:bz_cli_proto",
        "//bz/app/bz_subscription_proto:bz_subscription_proto",
    ],
)
