
oncall("build_infra")

rust_library(
    name = "bz_cmd_docs_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:clap",
        "third_party//rust:regex",
        "third_party//rust:termimad",
        "//app/bz_cli_proto:bz_cli_proto",
        "//app/bz_client_ctx:bz_client_ctx",
        "//app/bz_error:bz_error",
        "//app/bz_query:bz_query",
        "//deps/gazebo/dupe:dupe",
    ],
)
