
oncall("build_infra")

rust_library(
    name = "bz_downward_api",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "third_party//rust:async-trait",
        "third_party//rust:tracing",
        "//app/bz_error:bz_error",
        "//deps/bz_hash:bz_hash",
    ],
)
