load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "buck2_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "//bz/app/bz_build_api:buck2_build_api",
        "//bz/app/bz_common:buck2_common",
        "//bz/app/bz_core:buck2_core",
        "//bz/app/bz_error:buck2_error",
        "//bz/app/bz_events:buck2_events",
        "//bz/app/bz_interpreter:buck2_interpreter",
        "//bz/app/bz_interpreter_for_build:buck2_interpreter_for_build",
        "//bz/app/bz_node:buck2_node",
        "//bz/app/bz_transition:buck2_transition",
        "//bz/app/bz_util:buck2_util",
        "//bz/dice/dice:dice",
        "//bz/gazebo/dupe:dupe",
        "//bz/gazebo/gazebo:gazebo",
        "//bz/starlark-rust/starlark:starlark",
    ],
)
