
oncall("build_infra")

rust_test(
    name = "bz_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "third_party//rust:ctor",
        "third_party//rust:futures",
        "third_party//rust:indoc",
        "third_party//rust:serde_json",
        "third_party//rust:tokio",
        "//app/bz_build_api:bz_build_api",
        "//app/bz_common:bz_common",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_events:bz_events",
        "//app/bz_interpreter:bz_interpreter",
        "//app/bz_interpreter_for_build:bz_interpreter_for_build",
        "//app/bz_node:bz_node",
        "//app/bz_transition:bz_transition",
        "//app/bz_util:bz_util",
        "//deps/dice/dice:dice",
        "//deps/gazebo/dupe:dupe",
        "//deps/gazebo/gazebo:gazebo",
        "//deps/starlark-rust/starlark:starlark",
    ],
)
