load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bz_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "//bz/app/bz_build_api:bz_build_api",
        "//bz/app/bz_common:bz_common",
        "//bz/app/bz_core:bz_core",
        "//bz/app/bz_error:bz_error",
        "//bz/app/bz_events:bz_events",
        "//bz/app/bz_interpreter:bz_interpreter",
        "//bz/app/bz_interpreter_for_build:bz_interpreter_for_build",
        "//bz/app/bz_node:bz_node",
        "//bz/app/bz_transition:bz_transition",
        "//bz/app/bz_util:bz_util",
        "//bz/deps/dice/dice:dice",
        "//bz/deps/gazebo/dupe:dupe",
        "//bz/deps/gazebo/gazebo:gazebo",
        "//bz/deps/starlark-rust/starlark:starlark",
    ],
)
