oncall("golang")

prelude = native
go_package = prelude.go_library

prelude.cxx_library(
    name = "clib",
    srcs = ["lib.c"],
    public_include_directories = ["."],
    raw_headers = glob([
        "headers/*.h",
    ]),
)

go_package(
    name = "golib",
    package_name = "buck2/tests/prelude/go/cgo/include_dir/golib",
    cgo = True,
    deps = [":clib"],
)
