
oncall("build_infra")

rust_library(
    name = "bz_re_configuration",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//deps/allocative/allocative:allocative",
        "//app/bz_common:bz_common",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
    ],
)
