
oncall("build_infra")

rust_library(
    name = "bz_errorformat",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "third_party//rust:fancy-regex",
        "third_party//rust:nom",
        "third_party//rust:tracing",
        "//app/bz_error:bz_error",
    ],
)
