load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_errorformat",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:fancy-regex",
        "fbsource//third-party/rust:nom",
        "fbsource//third-party/rust:tracing",
        "//bz/app/bz_error:bz_error",
    ],
)
