load("//rules:cram.bzl", "cram_test")

oncall("build_infra")

cram_test(
    name = "integration",
    srcs = glob([
        "*.t",
        "fixtures/**/*",
    ]),
    env = {
        "DEP_FILE_PROCESSOR": "$(exe prelude//cxx/tools:dep_file_processor)",
    },
)
