
oncall("build_infra")

rust_library(
    name = "bz_miniperf_proto",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "third_party//rust:bincode",
    ],
    deps = [
        "third_party//rust:serde",
        "//app/bz_data:bz_data",
        "//deps/gazebo/dupe:dupe",
    ],
)
