load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bz_miniperf_proto",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:bincode",
    ],
    deps = [
        "fbsource//third-party/rust:serde",
        "//bz/app/bz_data:bz_data",
        "//bz/gazebo/dupe:dupe",
    ],
)
