load("//tests:buck_e2e.bzl", "bz_core_tests")

oncall("build_infra")

bz_core_tests(
    target_extra_attrs = {
        "test_completion": {
            "env": {
                "BUCK2_COMPLETION_VERIFY": "$(location //deps/completion_verify:completion_verify)",
            },
            "skip_for_os": ["windows"],
        },
    },
)
