
oncall("build_infra")

rust_library(
    name = "bz_query_parser",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "third_party//rust:derive_more",
        "third_party//rust:enum-map",
        "third_party//rust:nom",
        "third_party//rust:nom-language",
        "//app/bz_error:bz_error",
        "//app/bz_util:bz_util",
        "//deps/gazebo/dupe:dupe",
        "//deps/gazebo/gazebo:gazebo",
    ],
)
