load("@fbcode//bz/tests:buck_e2e.bzl", "bz_e2e_test")

oncall("rust_devx")

bz_e2e_test(
    name = "test_rust_project",
    srcs = [
        "test_rust_project.py",
    ],
    test_with_compiled_buck2 = False,
    test_with_deployed_buck2 = True,
    deps = [
        "//bz/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
