
oncall("build_infra")

rust_library(
    name = "bz_profile",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [],
    deps = [
        "third_party//rust:inferno",
        "//app/bz_cli_proto:bz_cli_proto",
        "//app/bz_core:bz_core",
        "//app/bz_error:bz_error",
        "//app/bz_fs:bz_fs",
        "//app/bz_interpreter:bz_interpreter",
        "//deps/starlark-rust/starlark:starlark",
    ],
)
