load("//tests:buck_e2e.bzl", "bz_e2e_test")

oncall("build_infra")

bz_e2e_test(
    name = "test_targets",
    srcs = ["test_targets.py"],
)

bz_e2e_test(
    name = "test_targets_inplace",
    srcs = ["test_targets_inplace.py"],
)
