load("//:rules/proto_defs.bzl", "proto_srcs", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "bz_test_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bz_test_proto.proto",
    deps = [
        "third_party//rust:prost-types",
        "//app/bz_data:bz_data",
        "//app/bz_host_sharing_proto:bz_host_sharing_proto",
    ],
)

proto_srcs(
    name = "bz_test_proto.proto",
    srcs = [
        "test.proto",
        "test_status.proto",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//app/bz_data:data_proto",
    ],
)
