load("@fbcode//bz:rules/proto_defs.bzl", "proto_srcs", "rust_protobuf_library")
load("@fbcode_macros//build_defs/lib:oss.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "bz_test_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bz_test_proto.proto",
    deps = [
        "fbsource//third-party/rust:prost-types",
        "//bz/app/bz_data:bz_data",
        "//bz/app/bz_host_sharing_proto:bz_host_sharing_proto",
    ],
)

proto_srcs(
    name = "bz_test_proto.proto",
    srcs = [
        "test.proto",
        "test_status.proto",
    ],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("//bz/app/bz_data:data_proto"),
    ],
)
