
oncall("build_infra")

filegroup(
    name = "tests",
    srcs = glob([
        "src/**/*.golden",
        "src/**",
    ]),
)

rust_test(
    name = "bz_error_tests",
    srcs = glob(["src/**/*.rs"]),
    env = {
        # Some of our tests include testcase files relative to CARGO_MANIFEST_DIR.
        # This is a hack that allows both `cargo test` and `buck test` to work.
        "CARGO_MANIFEST_DIR": "$(location :tests)",
    },
    deps = [
        "third_party//rust:anyhow",
        "//app/bz_error:bz_error",
        "//app/bz_util:bz_util",
        "//deps/starlark-rust/starlark:starlark",
    ],
)
